// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4v_A5L1DX8Z1GXL5Atr2sZozIQ0Ob5NE',
    appId: '1:1066889066685:web:8ad6bbe20d033df2c19fd4',
    messagingSenderId: '1066889066685',
    projectId: 'mood-diary-72c7f',
    authDomain: 'mood-diary-72c7f.firebaseapp.com',
    storageBucket: 'mood-diary-72c7f.firebasestorage.app',
    measurementId: 'G-5VHLZN1LCY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPikKUkKvc7m1nevsUZBWkSjycZHSxCKI',
    appId: '1:1066889066685:android:b1c66f2c5bb12dcbc19fd4',
    messagingSenderId: '1066889066685',
    projectId: 'mood-diary-72c7f',
    storageBucket: 'mood-diary-72c7f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUYgNhNtZAXUPOR1L9W2fsYCUP3wm_hGw',
    appId: '1:1066889066685:ios:61b54edcca04b50ec19fd4',
    messagingSenderId: '1066889066685',
    projectId: 'mood-diary-72c7f',
    storageBucket: 'mood-diary-72c7f.firebasestorage.app',
    iosClientId: '1066889066685-7glsebetfeit1klo9jbd4ecfkb1kak05.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUYgNhNtZAXUPOR1L9W2fsYCUP3wm_hGw',
    appId: '1:1066889066685:ios:61b54edcca04b50ec19fd4',
    messagingSenderId: '1066889066685',
    projectId: 'mood-diary-72c7f',
    storageBucket: 'mood-diary-72c7f.firebasestorage.app',
    iosClientId: '1066889066685-7glsebetfeit1klo9jbd4ecfkb1kak05.apps.googleusercontent.com',
    iosBundleId: 'com.example.moodDiary',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4v_A5L1DX8Z1GXL5Atr2sZozIQ0Ob5NE',
    appId: '1:1066889066685:web:d99b5ff6666875bcc19fd4',
    messagingSenderId: '1066889066685',
    projectId: 'mood-diary-72c7f',
    authDomain: 'mood-diary-72c7f.firebaseapp.com',
    storageBucket: 'mood-diary-72c7f.firebasestorage.app',
    measurementId: 'G-MWSVB693QF',
  );
}
